import type { Metadata } from 'next';
import './globals.css';
import { raleway } from '@/lib/fonts';
import Header from '@/components/Header';

export const metadata: Metadata = {
  title: 'Sclera',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${raleway.variable} relative`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
