import type { Metadata } from 'next';
import './globals.css';
import { raleway } from '@/lib/fonts';

export const metadata: Metadata = {
  title: 'Sclera',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={raleway.variable}>{children}</body>
    </html>
  );
}
